### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by nprail** [beevelop/corci#1]
I just came across this and I love the idea! Is the project still being developed?

**Comment by beevelop** [comment]
Unfortunately I do not actively maintain CorCI anymore as there are quite simpler solutions possible today (e.g. using GitLab CI with OS X Runner) and a few providers launched really good (and mostly working) alternatives to PhoneGap (e.g. Ionic Build).

Nonetheless I guess CorCI might still work with a few changes. If you stumble upon any problems or if you have questions concerning the architecture just open an issue or drop me a mail.
